### ISSUE TITLE
OnActivityResult not handle properly?

### ISSUE THREAD

**Issue by imramsuthakar** [paytabscom/paytabs-android-library-sample#1]
Hi,

 I'm using this SDK to make a payment, it will work fine the payment is completed I attached the screenshot when I click the back button it will work fine but when I click the system back button while I'm in the Completed screen i'm getting the data as null in the onActivityresult. so we are not able to find transaction is either success or failure. so please resolve this.

![Screenshot_20190828-164559](https://user-images.githubusercontent.com/6889844/63852059-10d26c00-c9b5-11e9-8c0d-f19e63c5869e.png)

**Comment by RamyHegazy** [comment]
@imramsuthakar We already fixed this issue if you are using the latest one v3.0.3

This week we are going to release a new version, which will remove the result page.

**Comment by imramsuthakar** [comment]
Thanks for the update!

**Comment by RamyHegazy** [comment]
@imramsuthakar Please check the latest SDK v4.0.0 https://github.com/paytabscom/paytabs-android-library-sample

**Comment by VivekMakwana24** [comment]
@imramsuthakar Hello, Can you help me for my above mentioned issue?

**Comment by imramsuthakar** [comment]
Will check and let you know Today.

**Comment by VivekMakwana24** [comment]
@imramsuthakar Thanks

**Comment by imramsuthakar** [comment]
Working fine
