### ISSUE TITLE
Technical Error occured - Retry Transaction

### ISSUE THREAD

**Issue by Mubark-p** [paytabscom/paytabs-android-library-sample#10]
when i use meda or visa card in live account  return technical error

**Comment by mohamedkhairy953** [comment]
Hello 
could you please provide us with more information to trace down the issue

**Comment by Mubark-p** [comment]
I used SDK 4.0.0 and followed the instructions in the document, and I tested through the 41111111111 test cards, and the operations were completed successfully. When transferring the account to Live and using a real mada card, the following error appears to me: "technical error try again"
Then I used a Visa card and it gives me the same message
here variables that i used:
 intent.putExtra(PaymentParams.ADDRESS_BILLING, address)
    intent.putExtra(PaymentParams.CITY_BILLING, "Riyadh")
    intent.putExtra(PaymentParams.STATE_BILLING, "Riyadh")
    intent.putExtra(PaymentParams.COUNTRY_BILLING, "SAU")
    intent.putExtra(PaymentParams.POSTAL_CODE_BILLING, "00966") 
 intent.putExtra(PaymentParams.ADDRESS_SHIPPING, address)
    intent.putExtra(PaymentParams.CITY_SHIPPING, "Riyadh")
    intent.putExtra(PaymentParams.STATE_SHIPPING, "Riyadh")
    intent.putExtra(PaymentParams.COUNTRY_SHIPPING, "SAU")
    intent.putExtra(PaymentParams.POSTAL_CODE_SHIPPING, "00966")

**Comment by mohamedkhairy953** [comment]
Are you using Pt1 or Pt2 version 
And please find provide me with the flow. When exactly this error appears? 
And if you provide me with the response code from onActivityResult method it will be helpful.

**Comment by Mubark-p** [comment]
using Pt1 version

**Comment by Mubark-p** [comment]
Click on Checkout. And call the library by the Pay Tabs. The screen for entering the card’s data appears. Enter the data and press Pay.
The total is shown with the currency symbol SAR

**Comment by Mubark-p** [comment]
![WhatsApp Image 2020-11-26 at 17 31 15](https://user-images.githubusercontent.com/64717588/100493672-48950a00-314a-11eb-903b-4252609fc7d0.jpeg)

**Comment by mohamedkhairy953** [comment]
What is your Merchant id ?

**Comment by Mubark-p** [comment]
10070940

**Comment by mohamedkhairy953** [comment]
please make sure you pass the address without special characters

**Comment by Mubark-p** [comment]
billing of address  ? i send location  address from google maps

**Comment by mohamedkhairy953** [comment]
yes try to remove the special character "," after receiving it from google maps

**Comment by Mubark-p** [comment]
i will try and send feedback thanks ^^

**Comment by mohamedkhairy953** [comment]
and if you pass Arabic characters, please make sure to pass it in English instead

**Comment by mohamedkhairy953** [comment]
the reason behind this error is that the processor rejecting the transaction so we are trying to figure out the cause
