### ISSUE TITLE
No Documentation on website

### ISSUE THREAD

**Issue by majdkz97** [paytabscom/paytabs-android-library-sample#11]
[documentation](https://dev.paytabs.com/docs/android/)

Is not working
Please Solve this issue soon

**Comment by mohamedkhairy953** [comment]
You can find the integration instructions through the readme file

**Comment by mohamedkhairy953** [comment]
we are working on new updates regarding the doc files

**Comment by majdkz97** [comment]
@mohamedkhairy953 

Can you help from where to get PaymentParams.**SECRET_KEY**,
It's not Explained in the Readme file and there is no documentation

**Comment by mohamedkhairy953** [comment]
You need to make merchant account on paytabs.com

**Comment by majdkz97** [comment]
![image](https://user-images.githubusercontent.com/49554262/104125483-a62e9000-535f-11eb-92ab-1acdbe211d3a.png)

Yes I have one

Can you tell me from where?
@mohamedkhairy953

**Comment by majdkz97** [comment]
@mohamedkhairy953 
@ahmed-mahdi-pt 
@paytabscom 
Please help me here
I have deadline 

I Still can't find **SecretKey**

**Comment by mustafaanan** [comment]
@majdkz97 Please send an email with this to customercare@paytabs.com and attach the merchant Id in mail.
