### ISSUE TITLE
In updated SDK (5.0.4) can we use any scanner option to scan credit card information? 

### ISSUE THREAD

**Issue by umer2686** [paytabscom/paytabs-android-library-sample#12]

**Comment by mohamedkhairy953** [comment]
There is a scnner in the 5.0.4
Please provide us with more information about the issue

**Comment by umer2686** [comment]
![Screenshot_1609933742](https://user-images.githubusercontent.com/16831167/103777419-a9213c00-5052-11eb-9c99-b7171ca4c2a5.png)

can you share some screenshots and guide me about that option bcz currently I am using 5.0.4 SDK but not found any option that scans my credit card information and fills the paytabs required fields.

my requirement this
![blinkcard-simple_i1920](https://user-images.githubusercontent.com/16831167/103777964-73308780-5053-11eb-8aa9-84497c0329be.png)

**Comment by mohamedkhairy953** [comment]
implementation 'cards.pay:paycardsrecognizer:1.1.0

Please add this line to your dependencies
This will fix the issue ISA

**Comment by umer2686** [comment]
Thank you. it is working now.
