### ISSUE TITLE
Hi Team! in latest SDK 5.0.4 can we prepopulate credit card information in required fields like (Card holder name, Card # and expiry date) ?  

### ISSUE THREAD

**Issue by umer2686** [paytabscom/paytabs-android-library-sample#13]
Hi Team! in the latest SDK 5.0.4 can we prepopulate credit card information in required fields (see attached image) like (Cardholder name, Card #, and expiry date)?

![Screenshot_1609933742](https://user-images.githubusercontent.com/16831167/103905933-0f749000-5121-11eb-980d-8a6f80483f3a.png)

**Comment by mohamedkhairy953** [comment]
No, you can not do this from the SDK.
To do this, you have to integrate directly with PayTabs APIs and apply whatever in UI. But this requires PCI compliance.
Please check this wit out support team customercare@paytabs.com
