### ISSUE TITLE
Does the android SDK supports tokenization

### ISSUE THREAD

**Issue by MahmoudMB** [paytabscom/paytabs-android-library-sample#14]
Dear Team, 

regarding using the saved card details in another payments, 
I notice that the token and tokenPassword and tokenEmail all of them is set to null and it is not getting the value that I am sending to the activity. 

Does the Mobile SDK support the ExistCustomer and that the user do not need to enter the card again and use the token in case it was already generated before ? and why are these attributes is set to null ? 

thanks

<img width="716" alt="Screen Shot 2021-01-18 at 4 51 10 PM" src="https://user-images.githubusercontent.com/23612742/104923640-62fe9d80-59ad-11eb-9e7b-51bbbc316148.png">

**Comment by mohamedkhairy953** [comment]
Yes tokenization is enabled in the sdk.

**Comment by MahmoudMB** [comment]
@mohamedkhairy953  
but why the values are set to null ?

**Comment by MahmoudMB** [comment]
the values are not retrieved from the intent

**Comment by MahmoudMB** [comment]
@mohamedkhairy953 

I mean when I pass the token and isExitsCustomer,  to the PayTabActivity.

its forced to be null for the token and false for isExitsCustomer.

So, why does this happen ?

**Comment by MahmoudMB** [comment]
@mohamedkhairy953 @mustafaanan @ahmed-mahdi-pt @paytabscom 

Dear Team.

could any one please confirm if I can set this parameter (IS_EXISTING_CUSTOMER )  to true.

and also passing:
CUSTOMER_EMAIL
CUSTOMER_PASSWORD
TOKEN 

and it should not ask the user to enter his card details again, but thats not happening. 

its just ignoring the tokenization values that I am passing. 


is this feature available in the mobile sdks ? 

and if it is not, how we should use it ?

**Comment by mohamedkhairy953** [comment]
In this version, passing the token is not available in mobile SDK.
Using the token in mobile SDK will be available in the next version soon
