### ISSUE TITLE
Secret Key in PT V2

### ISSUE THREAD

**Issue by Mubark-p** [paytabscom/paytabs-android-library-sample#16]
Where can I find the the secret key in the new version? There are no instructions or explanations regarding the linking. I made an email to the support and I was given all old links that do not explain where to find the secret key ?????????????

**Comment by alhazmy13** [comment]
same issue here

**Comment by mohamedkhairy953** [comment]
Hello Please contact Customercare@Paytabs.com and ask for your client key and server key for the mobile SDK to integrate with PT2 Version.
