### ISSUE TITLE
JSON format toast message

### ISSUE THREAD

**Issue by mohamadabdelhamid** [paytabscom/paytabs-android-library-sample#19]
I'm trying to use PT2 but it always shows this Toast message "Request must be in JSON format with content type application/json".
@mohamedkhairy953 Can you please tell how to solve this?

**Comment by mohamedkhairy953** [comment]
Please contact customercare@paytabs.com 
to solve this issue as it may be related to your profile data.

**Comment by ateftawfeq** [comment]
same issue

**Comment by mohamedkhairy953** [comment]
I think the problem is that you are not using the mobile sdk keys server and client keys, and using the web keys instead

**Comment by ateftawfeq** [comment]
Request must be in JSON format with content type application/json


في ثلاثاء، ٣٠ مارس، ٢٠٢١ في ٨:٣٠ م، كتب Mooahmed khairy sallam <
***@***.***>:

**Comment by mohamedkhairy953** [comment]
Please contact customercare@paytabs.com
to generate your mobile sdk keys.
