### ISSUE TITLE
Technical Error occured - Retry Transaction

### ISSUE THREAD

**Issue by VivekMakwana24** [paytabscom/paytabs-android-library-sample#2]
![Screenshot_1567574762](https://user-images.githubusercontent.com/48508009/64227846-9d73b180-cf02-11e9-9139-7cd757171eb6.png)

Hello, 
When i am trying to pay using Test Cards then i am receiving this error. Please check the screen shot. 
So what should i do?

Update: 
Its working in USD currency. but i want it to work in Egyptian currency i.e EGP. 
Any solution?

**Comment by gardencoder** [comment]
@VivekMakwana24 Please send mail your merchant id to support@paytabs.com
