### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by elienaj** [paytabscom/paytabs-android-library-sample#20]
Hello Team,
I'm getting the below error.
" Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
        at com.payment.paymentsdk.PaymentSdkActivity$Companion.startCardPayment"
Can you help please.

**log error** 
[Fatal Error] payment-sdk-6.0.1-beta11.pom:2:3: The markup in the document preceding the root element must be well-formed.

**mainactivity :**
private void startPayment() {
        String profileId = "xxx";
        String serverKey = "xxxxx";
        String clientKey = "xxxxxxxx";

        PaymentSdkLanguageCode locale = PaymentSdkLanguageCode.EN;
        String screenTitle = "Test SDK";
        String cartId = "123456";
        String cartDesc = "cart description";
        String currency = "AED";
        double amount = 20.0;
        Toast.makeText(getApplicationContext(),"Hello 0",Toast.LENGTH_SHORT).show();
        PaymentSdkTokenise tokeniseType = PaymentSdkTokenise.NONE; // tokenise is off

        PaymentSdkTokenFormat tokenFormat = new PaymentSdkTokenFormat.Hex32Format();

        PaymentSdkBillingDetails billingData = new PaymentSdkBillingDetails(
                "City",
                "Country",
                "email1@domain.com",
                "name ",
                "phone", "state",
                "address street", "zip"
        );

        PaymentSdkShippingDetails shippingData = new PaymentSdkShippingDetails(
                "City",
                "Country",
                "email1@domain.com",
                "name ",
                "phone", "state",
                "address street", "zip"
        );
        PaymentSdkConfigurationDetails configData = new PaymentSdkConfigBuilder(profileId, serverKey, clientKey, amount, currency)
                .setCartDescription(cartDesc)
                .setLanguageCode(locale)
                .setBillingData(billingData)
                .setMerchantCountryCode("OM") // ISO alpha 2
                .setShippingData(shippingData)
                .setCartId(cartId)
                .showBillingInfo(false)
                .showShippingInfo(true)
                .forceShippingInfo(true)
                .setScreenTitle(screenTitle)
                .build();
        PaymentSdkActivity.startCardPayment(getParent(), configData, this);
    }

    @Override
    public void onError(@NotNull PaymentSdkError paymentSdkError) {
        Toast.makeText(getApplicationContext(),"Hello 1" +paymentSdkError.getMsg(),Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onPaymentCancel() {
        Toast.makeText(getApplicationContext(),"Hello 2",Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onPaymentFinish(@NotNull PaymentSdkTransactionDetails paymentSdkTransactionDetails) {
        Toast.makeText(getApplicationContext(),"Hello 3",Toast.LENGTH_SHORT).show();
    }
    
    _**build.gragle**_

    configurations.all {
    resolutionStrategy {
        exclude group: "org.jetbrains.kotlinx", module: "kotlinx-coroutines-debug"
    }
}

 implementation 'com.paytabs:payment-sdk:6.0.1-beta11'

  maven { url "http://pay.cards/maven" }
        maven {
            url  "https://dl.bintray.com/paytabsandroidsdk/paytabs-sdk"
        }

**Comment by mohamedkhairy953** [comment]
Please check that you are not passing any null values to the parameters, and make shure that getParent() does not return null or simply pass this keyword instead.

**Comment by elienaj** [comment]
Hello @mohamedkhairy953,
i replaced getParent() with this.
Now I'm getting a new error. INVALID billing country code.

 private void startPayment() {
        String profileId = "640xx";
        String serverKey = "SKJNN2RMTB-JBJG2692LH-xxxxxx";
        String clientKey = "CGKMMB-KP9262-6TMGPM-xxxx";

        PaymentSdkLanguageCode locale = PaymentSdkLanguageCode.EN;
        String screenTitle = "Test SDK";
        String cartId = "123456";
        String cartDesc = "cart description";
        String currency = "OMR";
        double amount = 20.0;
       // Toast.makeText(getApplicationContext(),"Hello 0",Toast.LENGTH_SHORT).show();
        PaymentSdkTokenise tokeniseType = PaymentSdkTokenise.NONE; // tokenise is off



        PaymentSdkTokenFormat tokenFormat = new PaymentSdkTokenFormat.Hex32Format();


        PaymentSdkBillingDetails billingData = new PaymentSdkBillingDetails(
                "Oman",
                "Muscat",
                "elie.h.najem@gmail.com",
                "Elie Najem",
                "+96895919143",
                "state",
                "way 3043, villa 689, shati al qurum",
                "123"
        );

        PaymentSdkShippingDetails shippingData = new PaymentSdkShippingDetails(
                "Oman",
                "Muscat",
                "elie.h.najem@gmail.com",
                "Elie Najem",
                "+96895919143", "state",
                "way 3043, villa 689, shati al qurum", "123"
        );
        
        PaymentSdkConfigurationDetails configData = new PaymentSdkConfigBuilder(profileId, serverKey, clientKey, amount, currency)
                .setCartDescription(cartDesc)
                .setLanguageCode(locale)
                .setBillingData(billingData)
                .setMerchantCountryCode("OM") // ISO alpha 2
                .setShippingData(shippingData)
                .setCartId(cartId)
                .showBillingInfo(false)
                .showShippingInfo(true)
                .forceShippingInfo(true)
                .setScreenTitle(screenTitle)
                .build();
        PaymentSdkActivity.startCardPayment(this, configData, this);
    }

    @Override
    public void onError(@NotNull PaymentSdkError paymentSdkError) {
        Toast.makeText(getApplicationContext(),"Hello 1" +paymentSdkError.getMsg(),Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onPaymentCancel() {
        Toast.makeText(getApplicationContext(),"Hello 2",Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onPaymentFinish(@NotNull PaymentSdkTransactionDetails paymentSdkTransactionDetails) {
        Toast.makeText(getApplicationContext(),"Hello 3",Toast.LENGTH_SHORT).show();
    }

**Comment by mohamedkhairy953** [comment]
Billing and shipping countries are 2 digit ISO

**Comment by mohamedkhairy953** [comment]
Please make sure that you are passing city in the first parameter and country code in the second parameter

**Comment by elienaj** [comment]
Hello @mohamedkhairy953,
When i press on pay now, I'm getting the below message
"Request must be in JSON format with content type application/json"
can you help please

**Comment by mohamedkhairy953** [comment]
https://github.com/paytabscom/paytabs-android-library-sample/blob/PT2/common_issues.md
