### ISSUE TITLE
invalid merchant credentials

### ISSUE THREAD

**Issue by FatimaSalman** [paytabscom/paytabs-android-library-sample#21]
I have this message error when call payment function 
"invalid merchant credentials" 

I am use the last sdk 5.0.7 what is the solution for this issue ?
thanks 
![WhatsApp Image 2021-04-02 at 12 52 47 AM](https://user-images.githubusercontent.com/4582250/113414294-59d67780-93c5-11eb-8929-254bd4b194d9.jpeg)

**Comment by mohamedkhairy953** [comment]
Often this message appears in case of invalid secret, email or invalid
region please check these params.

Please contact ***@***.*** to migrate to PT2 as Pt1 will be
deprecated soon, and also they can help you to check the invalid
credentials.

**Comment by FatimaSalman** [comment]
thanks for replay me, you mean contact with support to migrate pt2 as pt1 

but I have account in pt2 == the secret key not found in the dashboard, how I get it ?

**Comment by mohamedkhairy953** [comment]
When you contact ***@***.*** they will provide you with the
client key and the server key for the mobile sdk and follow this link to
fully migrate.
https://github.com/paytabscom/paytabs-android-library-sample/blob/PT2

**Comment by FatimaSalman** [comment]
https://github.com/paytabscom/paytabs-android-library-sample/blob/PT2

this url not work == give me page not found

**Comment by mohamedkhairy953** [comment]
https://github.com/paytabscom/paytabs-android-library-sample/tree/PT2

**Comment by FatimaSalman** [comment]
thanks you

**Comment by FatimaSalman** [comment]
I am download your code and change server key , client key and profile id with my data 
but this message appear **(authorization failed. check authorization header)**
 I don't know why? and how to solve it?

**Comment by mohamedkhairy953** [comment]
Those might not be the valid keys for the mobile sdk.
Please send your issue to ***@***.*** with these credentials
to check if they are the mobile keys.

**Comment by FatimaSalman** [comment]
I don't see in your code mobile key == just server and client

**Comment by mohamedkhairy953** [comment]
Yes server key and client.
Each merchant has two server keys and two client keys one pair for the web
apis and the other for the mobile apis.
So if you are getting invalid credentials this might be because you are not
passing the mobile keys.
***@***.*** can confirm this if that is the case.

**Comment by mohamedkhairy953** [comment]
customercare@Paytabs.com

**Comment by mohamedkhairy953** [comment]
also, validate that you are using the correct merchantCountryCode

**Comment by FatimaSalman** [comment]
I contact with the support and now appear other errors and I don't see it in the logcat in android studio 

![WhatsApp Image 2021-04-05 at 12 37 49 PM](https://user-images.githubusercontent.com/4582250/113560707-191c6f80-960c-11eb-9c23-f6965d72208c.jpeg)

**Comment by FatimaSalman** [comment]
thanks you it's solved :) best wishes for you

**Comment by mohamedkhairy953** [comment]
Hello Fatma,
Our support team will send you all the credentials needed to pass this
issue, please let me know the status after using it.
