### ISSUE TITLE
Using Test card displaying toast message "Authentication failed. Check authentication header."

### ISSUE THREAD

**Issue by mostasim** [paytabscom/paytabs-android-library-sample#22]
How to fix this?
I am using test card showing In the developer section to PAY NOW.

**Comment by mohamedkhairy953** [comment]
Hello 
Please take a look in these common issues you will find the correct answer there.

https://github.com/paytabscom/paytabs-android-library-sample/blob/PT2/common_issues.md

**Comment by mohamedkhairy953** [comment]
This issue mainly happens because of incorrect keys so, please contact customercare@paytabs.com to check your correct ones.

**Comment by niranjansheshadri** [comment]
Hi, We are trying to integrate the PT2 Android SDK getting **Authentication failed. Check authentication header.** error. I have checked the keys, keys looks to be correct as the same keys are working while calling API web application.

**Comment by mostasim** [comment]
I think you should check currency format that you provided. In my case i
was trying with "AED" and getting authentication error. Then i just changed
it to "SAR" then this error gone.
I don’t know what is related to that currency with authentication.
