### ISSUE TITLE
App restart when calling startCardPayment()

### ISSUE THREAD

**Issue by ramyassaf** [paytabscom/paytabs-android-library-sample#24]
We are facing a very weird issue when clicking pay with card and calling the below function on android:

PaymentSdkActivity.startCardPayment(requireActivity(), configData, callback = this)

The problem is that the app is restarting and auto cleaning the logs, so we are not able to see the problem.
And the weird thing is that on some android devices it's working fine, 3 devices out of 10.

Any idea what's the problem here?

**Comment by mohamedkhairy953** [comment]
Please provide us with the following:
.the version you are using
.the parameters passed to configData object.
. android versions and phones data where this issue occurs.

**Comment by ramyassaf** [comment]
Good morning Mohamed,

- The version of sdk is 6.1.8 (implementation 'com.paytabs:payment-sdk:6.1.8')
- The configData params: profileId, serverkey, clientKey, amount, currencyCode
- For the android version, it's random, we tested on android 7, 8, 9, 10 & 11, we are having the problem on all android version, but on a small number of devices it's working, for example on android 9 it's working on 1 device but not the others.

**Comment by mohamedkhairy953** [comment]
Are you using kotlin or java

**Comment by ramyassaf** [comment]
Kotlin

**Comment by mohamedkhairy953** [comment]
Update the version to 6.1.9 and If it did not work
Please create a meeting on zoom and send me the link on 
m.khairy@Paytabs.com 
tomorrow at 3 pm.

**Comment by ramyassaf** [comment]
I tried with version 6.1.9, still the same.
Can we make it at 4PM GMT+3?

**Comment by mohamedkhairy953** [comment]
ok

**Comment by ramyassaf** [comment]
Hello Mohamed,

Did you receive my zoom link?

**Comment by ramyassaf** [comment]
Big Thank you @mohamedkhairy953 for you support

The problem was caused by a big drawable icon we used in .setMerchantIcon(drawable)
As per Mohamad's recommendation we used a png hosted on server and we passed the link to setMerchantIcon(http link of icon) instead of passing the drawable object.

This solved the app restarting problem.
