### ISSUE TITLE
Getting Error while updating Latest SDK for Android

### ISSUE THREAD

**Issue by mohsinbutt2020** [paytabscom/paytabs-android-library-sample#25]
Take a look at this error. when i add the PayTabs Dependency in my project it,s giving this error.

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlinx.coroutines.debug.AgentPremain found in modules jetified-kotlinx-coroutines-core-jvm-1.4.2 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.2) and jetified-kotlinx-coroutines-debug-1.3 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.3)
     Duplicate class kotlinx.coroutines.debug.AgentPremain$installSignalHandler$1 found in modules jetified-kotlinx-coroutines-core-jvm-1.4.2 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.2) and jetified-kotlinx-coroutines-debug-1.3 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.3)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl found in modules jetified-kotlinx-coroutines-core-jvm-1.4.2 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.2) and jetified-kotlinx-coroutines-debug-1.3 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.3)
     Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner found in modules jetified-kotlinx-coroutines-core-jvm-1.4.2 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.2) and jetified-kotlinx-coroutines-debug-1.3 (org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.3)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by mohamedkhairy953** [comment]
Please refer to the known issue part in the readme file
