### ISSUE TITLE
Shipping address not provide issue

### ISSUE THREAD

**Issue by miralsapariya** [paytabscom/paytabs-android-library-sample#26]
![image](https://user-images.githubusercontent.com/68226259/131837609-1664d921-7446-45e9-af5c-01cfb607e2cf.png)

I always passes the shipping address ..getting arror like above screenshot
 my code like below
 
   PaymentSdkShippingDetails data=new PaymentSdkShippingDetails();
        data.setAddressLine("B6, chandrapark");
        data.setCity("Rajkot");
        data.setCountryCode("+91");
        data.setName("miral");
        data.setPhone("9210568410");
        data.setEmail("patelmiral61@gmail.com");
        data.setState("Gujarat");
        data.setZip("360005");

  PaymentSdkConfigurationDetails configData = new PaymentSdkConfigBuilder(profileId, serverKey, clientKey, amount, currency)
                .setCartDescription(cartDesc)
                .setLanguageCode(locale)
               // .setBillingData(billingData)
                .setMerchantCountryCode("US") // ISO alpha 2
                .setShippingData(data)
                .setCartId(cartId)
                .showBillingInfo(false)
                .showShippingInfo(false)
                .forceShippingInfo(false)
                .setScreenTitle(screenTitle)
                              .build();

**Comment by mohamedkhairy953** [comment]
Hello,
The issue here is that you do not provide the billing object and you have to provide it, but the error message is wrong and it will be fixed next release.

Thank you.

**Comment by miralsapariya** [comment]
why it is compulsory to pass billing address and shipping address. In my project i will use this payment gateway for service base not selling goods. So no need such type of address. Is there any way we can bypass the billing and shipping address ....?

**Comment by mohamedkhairy953** [comment]
You can pass any fixed data in billing object that make it work, and shipping data are not required as long as you are passing forceShippingInfo with false.
But bypassing billing data technically not possible yet.

You can ask customercare@paytabs.com for more details regarding these requests.

**Comment by KhaledAlramam** [comment]
Closed due to inactivity
