### ISSUE TITLE
Request must be in JSON format with content type application/json - Android Native

### ISSUE THREAD

**Issue by skbhati199** [paytabscom/paytabs-android-library-sample#27]
I am using the 2.0.3-beta and trying to implement through demo example with my credentials but this error is returned
"Request must be in JSON format with content type application/json"

`{
  "callback": "none",
  "card_details": {
    "cvv": "123",
    "expiry_month": 11,
    "expiry_year": 2022,
    "pan": "4111111111111111"
  },
  "cart_amount": 20.0,
  "cart_currency": "AED",
  "cart_description": "cart description",
  "cart_id": "1234561774763047",
  "customer_details": {
    "city": "Dubai",
    "country": "AE",
    "email": "skbhati199@gmail.com",
    "ip": "255.255.255.255",
    "name": "Radwa al Moustafa ",
    "phone": "04-2219648",
    "state": "Dubai",
    "street1": "Near Mount Royal Hotel, Al Burj Street, Deira",
    "zip": "10371"
  },
  "paypage_lang": "EN",
  "profile_id": "57651",
  "return": "https://ptsdk-return.paytabs.com/1631007028206",
  "shipping_details": {
    "city": "Dubai",
    "country": "AE",
    "email": "abc@gmail.com",
    "ip": "",
    "name": "Radwa al Moustafa ",
    "phone": "04-2219648",
    "state": "Dubai",
    "street1": "Near Mount Royal Hotel, Al Burj Street, Deira",
    "zip": "10371"
  },
  "tran_class": "ecom",
  "tran_type": "auth", 
  "device_info": {
    "device_id": "",
    "app_id": "com.android.hltherasocialnetwork",
    "platform": "Android",
    "brand": "Xiaomi",
    "model": "Mi A3",
    "carrier": "",
    "os": "11",
    "version": "11",
    "app_version": "1.0",
    "sdk_version": "6.1.2",
    "timestamp": "1631007011925",
    "screen_width": "720",
    "screen_height": "1560",
    "app_lang": "en",
    "device_lang": "en",
    "connection": "wifi"
  }
}`

I am also attaching the API Debug console snapshot
Error show me
Request must be in JSON format with content type application/json

**Comment by Gautammer** [comment]
Hello, I am getting same error!
Any solution found?

**Comment by skbhati199** [comment]
I use webview in Android
