### ISSUE TITLE
[Android Kotlin] Need your support for PayTabs implementation

### ISSUE THREAD

**Issue by itmanzzz** [paytabscom/paytabs-android-library-sample#4]
Dear Sir,

I'm Johnny, an android developer come from Vietnam.
Could u share with me a good way to implement this SDK?

![image](https://user-images.githubusercontent.com/5549954/90053872-44f98680-dd05-11ea-9de7-a5f596cbd0ed.png)

I'm seeing that need to give all the required fields. Can we skip some fields?

Thanks,

**Comment by Sajid-Ali** [comment]
package com.paytabs.paytabs_sdk.utils does not exist
import com.paytabs.paytabs_sdk.utils.PaymentParams;

I am getting this error while integrating any update?
