### ISSUE TITLE
How to start payment with saved cards

### ISSUE THREAD

**Issue by mohamadabdelhamid** [paytabscom/paytabs-android-library-sample#40]
What is the flow for starting a payment with the user's saved cards?
I'm trying to call the function you mentioned in your sample app `startPaymentWithSavedCards` but keep getting this error `PaymentSdkError(code=-1, msg=Please provide saved card info)`.
Any help?

**Comment by KhaledAlramam** [comment]
Issue fixed in 6.3.3
