### ISSUE TITLE
White screen while payment via saved card

### ISSUE THREAD

**Issue by chichi289** [paytabscom/paytabs-android-library-sample#42]
![1672989807339](https://user-images.githubusercontent.com/20377949/210951271-236683e0-2199-48ae-86e1-ca0299bc2c18.JPEG)

When we initiate payment by saved card [ **PaymentSdkActivity.startCardPayment()** ] then white screen is displayed for a second.

Paytabs library version :- com.paytabs:payment-sdk:6.2.12

How can we remove this white screen as it confuse users.

Thanks

**Comment by KhaledAlramam** [comment]
Kindly check version 6.4.0

**Comment by chichi289** [comment]
Hello @KhaledAlramam 

Now it loads white screen with ProgressBar.

Thanks
