### ISSUE TITLE
"Something went wrong!" while pay with new card in release build

### ISSUE THREAD

**Issue by chichi289** [paytabscom/paytabs-android-library-sample#43]
I have used paytabs android sdk version 6.4.4 as below

`customerImplementation('com.paytabs:payment-sdk:6.4.4') {
        exclude group: "com.paytabs", module: "scan-card"
    }`

I have also used proguard as below

-keep public class com.payment.paymentsdk.* {;}

-dontwarn com.paytabs.paytabscardrecognizer.cards.pay.paycardsrecognizer.sdk.Card
-dontwarn com.paytabs.paytabscardrecognizer.cards.pay.paycardsrecognizer.sdk.ScanCardIntent$Builder

-dontwarn com.paytabs.paytabscardrecognizer.cards.pay.paycardsrecognizer.sdk.ui.ScanCardActivity
-dontwarn com.paytabs.paytabscardrecognizer.cards.pay.paycardsrecognizer.sdk.ui.ScanCardRequest

But after upgrading the below things at my end Paytabs payment SDK in Android is not working in the **release apk**. It is working fine in **debug version**

- Android Studio Flamingo | 2022.2.1 Patch 1
- Android Gradle Plugin 8.0.1
- Java 17 support was added due to AGP 8.0.1

Please check the attached screenshot for the error I am getting.

![Screenshot_1683531106 (1)](https://user-images.githubusercontent.com/20377949/236774550-bd6157af-13f2-40d5-87e0-650c8791f649.png)

@KhaledAlramam Please do the needful 

Thanks

**Comment by muhammadalkady** [comment]
This issue was fixed. Please use the latest release.
