### ISSUE TITLE
Return URL does not start with expected value in Release variant

### ISSUE THREAD

**Issue by Hussein-Al-Zuhile** [paytabscom/paytabs-android-library-sample#44]
Hello Paytabs support team,

First, thanks for the hard work ❤️.
I am facing an issue when building Release apk and try to test the payment , I got the message: "Return URL does not start with expected value" in the onError() callback method.
I added these proguard rules:
-keep public class com.payment.paymentsdk.\*\*{*;}
-keep  class com.paytabs.pt2sdk.\*\*{ *; }

What I have noticed that the request body in the dashboard is obfuscated when I am using Release version, here is what I mean:
In Release mode:
![MicrosoftTeams-image (2)](https://github.com/paytabscom/paytabs-android-library-sample/assets/43495888/054e95df-8947-4dfa-a978-3773a877a86b)

In Debug mode:
![MicrosoftTeams-image (4)](https://github.com/paytabscom/paytabs-android-library-sample/assets/43495888/4d6f7346-b68e-4533-b243-dec7d027bd33)

Would you please tell me what the problem is and thanks for your time.

**Comment by KhaledAlramam** [comment]
Hi Hussein
Hope you are doing well

Could you share what version are you using ?

**Comment by Hussein-Al-Zuhile** [comment]
Hello Khaled,
Thanks for reaching out.

The used version is 6.4.7

**Comment by KhaledAlramam** [comment]
Could you try version
6.4.12
This issue was solved on it

**Comment by Hussein-Al-Zuhile** [comment]
Thanks, that's worked.
I will close the issue now.

**Comment by Hussein-Al-Zuhile** [comment]
Hello @KhaledAlramam,
Hope you are doing well,

The same issue reappeared, without changing anything, can you double-check it please.

**Comment by Hussein-Al-Zuhile** [comment]
It worked on 6.4.11 version though.
