### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by mshoaib1695** [paytabscom/paytabs-android-library-sample#5]
application crashes in release build while it is working fine in development.
any one face this issue earlier? 
need help

**Comment by RKSharma89** [comment]
Please add below rule in proguard file.
-keep class com.paytabs.paytabs_sdk.** { *; }

**Comment by mshoaib1695** [comment]
Thank You so much, it works for me

**Comment by josyvoxtron** [comment]
> Task :react-native-paytabs-sdk:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-paytabs-sdk:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:14: error: attribute cardCornerRadius (aka com.rn.paytabs:cardCornerRadius) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:14: error: attribute cardElevation (aka com.rn.paytabs:cardElevation) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute card_number_hint (aka com.rn.paytabs:card_number_hint) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute default_text_colors (aka com.rn.paytabs:default_text_colors) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_exp (aka com.rn.paytabs:include_exp) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_helper (aka com.rn.paytabs:include_helper) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_security (aka com.rn.paytabs:include_security) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_zip (aka com.rn.paytabs:include_zip) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute input_background (aka com.rn.paytabs:input_background) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:14: error: attribute cardCornerRadius (aka com.rn.paytabs:cardCornerRadius) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:14: error: attribute cardElevation (aka com.rn.paytabs:cardElevation) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute card_number_hint (aka com.rn.paytabs:card_number_hint) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute default_text_colors (aka com.rn.paytabs:default_text_colors) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_exp (aka com.rn.paytabs:include_exp) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_helper (aka com.rn.paytabs:include_helper) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_security (aka com.rn.paytabs:include_security) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_zip (aka com.rn.paytabs:include_zip) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute input_background (aka com.rn.paytabs:input_background) not found.
  error: failed linking file resources.

**Comment by MostafaGad1911** [comment]
@josyvoxtron 

do u find solution for this issue ???
