### ISSUE TITLE
application crashes when I press pay button.

### ISSUE THREAD

**Issue by josyvoxtron** [paytabscom/paytabs-android-library-sample#6]
I was trying to integrate Paytab SDK with my react native project, I am not able to create APK file after including react-native-paytab-sdk also app is not running in emulator. Please do support fixing the issue.
On emulator am getting error attached screenshots, application crashes when I press pay button.
![Screenshot_1603869136](https://user-images.githubusercontent.com/71818732/97425966-d22d9e00-1938-11eb-94b6-b0b7df1aa35f.png)
![Screenshot_1603869155](https://user-images.githubusercontent.com/71818732/97425975-d5c12500-1938-11eb-8ab4-d7328dbaa45e.png)

`> Task :react-native-paytabs-sdk:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-paytabs-sdk:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:14: error: attribute cardCornerRadius (aka com.rn.paytabs:cardCornerRadius) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:14: error: attribute cardElevation (aka com.rn.paytabs:cardElevation) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute card_number_hint (aka com.rn.paytabs:card_number_hint) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute default_text_colors (aka com.rn.paytabs:default_text_colors) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_exp (aka com.rn.paytabs:include_exp) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_helper (aka com.rn.paytabs:include_helper) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_security (aka com.rn.paytabs:include_security) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute include_zip (aka com.rn.paytabs:include_zip) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout\paytabs_fragment_payment.xml:134: error: attribute input_background (aka com.rn.paytabs:input_background) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:14: error: attribute cardCornerRadius (aka com.rn.paytabs:cardCornerRadius) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:14: error: attribute cardElevation (aka com.rn.paytabs:cardElevation) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute card_number_hint (aka com.rn.paytabs:card_number_hint) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute default_text_colors (aka com.rn.paytabs:default_text_colors) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_exp (aka com.rn.paytabs:include_exp) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_helper (aka com.rn.paytabs:include_helper) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_security (aka com.rn.paytabs:include_security) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute include_zip (aka com.rn.paytabs:include_zip) not found.
  D:\Josy-Projects\...\node_modules\react-native-paytabs-sdk\android\build\intermediates\res\merged\release\layout-ar\paytabs_fragment_payment.xml:137: error: attribute input_background (aka com.rn.paytabs:input_background) not found.
  error: failed linking file resources.
`

**Comment by mohamedkhairy953** [comment]
I think you missing some dependencies in your gradle
