### ISSUE TITLE
App crash after clicking the pay now button 

### ISSUE THREAD

**Issue by umeriqbal97** [paytabscom/paytabs-android-library-sample#9]
here is the exception:
  
Process: com.bestercapitalmedia.chiragh, PID: 12080
    java.lang.IllegalStateException: Fragment ProgressFragment{d81f481 (79897dfe-07c5-498a-a1f3-26675ff32a75)} not associated with a fragment manager.
        at androidx.fragment.app.Fragment.requireFragmentManager(Fragment.java:910)
        at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:245)
        at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
        at com.paytabs.paytabs_sdk.payment.ui.activities.SecurePaymentActivity.hideProgressBar(SecurePaymentActivity.java:176)
        at com.paytabs.paytabs_sdk.d3s.D3SView$1.onPageFinished(D3SView.java:158)
        at Qg.b(chromium-TrichromeWebViewGoogle.aab-stable-424018533:2)
        at sA.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-424018533:65)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mohamedkhairy953** [comment]
Hello|
Please specify the sdk version you use

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 
i am using following sdk version
paytabs_sdk-v5.0.0

**Comment by mohamedkhairy953** [comment]
https://github.com/paytabscom/paytabs-android-library-sample/blob/pt2_emulated/sdk/paytabs_sdk-v5.0.1.aar
please use this version and let me know if still there

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 ok i will let you know Thanks

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 it still there.  first time it works fine but after my second attemp it crash

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 on android 9 it working fine but on android 11 some time it crashes can you please guide me on this. i am looking forward for your response.

**Comment by mohamedkhairy953** [comment]
@umeriqbal97 I have tried  with android 11 but everything works fine here so I think we will need more details about the scenario, testing device, and merchant id  to look further into the issue 

Thank you

**Comment by mohamedkhairy953** [comment]
[paytabs_sdk-v5.0.1.zip](https://github.com/paytabscom/paytabs-android-library-sample/files/5548060/paytabs_sdk-v5.0.1.zip)
please try with this .aar file and let me know if it works to update the library.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 ok i will let you know thanks for your response.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 sorry for late. above sdk .zip that you provide it doesnot crash but it show dailog which is never stops. I am using the Google Pixel 2xl.
![Screenshot_20201118-153239](https://user-images.githubusercontent.com/56654074/99519671-fcaccd00-29b3-11eb-97a8-d0bd35d2d0c4.png)

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 Can you please guide on this. I am waiting for your response

**Comment by mohamedkhairy953** [comment]
I will check it out and let you know.
Could you check in different android 11 device and let me know.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 i have tried in (emulator android 11 version) Pixel 2. it working but it crash on physical device googlepixel 2xl. can you please check?

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 by mistakenly i press close button. I will let you know Thanks for your response

**Comment by mohamedkhairy953** [comment]
@umeriqbal97 
Please provide me with the card info you typed in this demo version.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 i am using test card for transaction purpose. here is the screen shot of test that i am using  
![testcard](https://user-images.githubusercontent.com/56654074/99954150-1d09cc80-2da4-11eb-8a4b-72779a563e29.PNG)

**Comment by mohamedkhairy953** [comment]
Could you check in different android 11 device and let me know.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953  recent version that you will provide in zip it shows loader in all version of android as i was mention it earlier with screen shot

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 basically it shows continuous loading on 3d secure simulation screen. looking forward for your response.

**Comment by umeriqbal97** [comment]
@mohamedkhairy953 thanks for your response it has been now fixed i am closing this issue.
